dairy_products_ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, add_product_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete-product/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="w-[1440px] h-20 px-20 bg-white shadow justify-start items-center inline-flex fixed top-0 left-0 z-40 w-screen">
    <div class="flex items-center">
        <div class="bg-gradient-to-r from-[#73daf1] to-[#eb7acb] bg-clip-text text-transparent text-[28px] font-sans font-bold md:text-[40px]">MyDairy</div>
    </div>
    <div class="grow shrink basis-0 h-[49px] justify-end items-center gap-5 flex">
        {% if user.is_authenticated %}
            <div class="hidden md:block text-black text-base font-sans font-normal">Welcome, {{ user.username }}</div>
            <a href="{% url 'main:logout' %}" class="hidden md:block relative px-4 py-3 bg-gradient-to-r from-[#73daf1] to-[#eb7acb] rounded-md justify-center items-center gap-2.5 flex transform transition duration-300 ease-in-out hover:scale-105 hover:shadow-lg">
                <div class="text-slate-50 text-xl font-sans font-bold">Logout</div>
            </a>
        {% endif %}
    </div>
    <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
            <svg class="hamburger w-6 h-6 text-[#a2e8f7]" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                <path d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
            <svg class="x-icon hidden w-6 h-6 text-[#a2e8f7]" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                <path d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </button>
    </div>
</nav>

<!-- Mobile menu -->
<div class="mobile-menu hidden md:hidden px-4 w-full md:max-w-full mt-24"> 
    <div class="pt-2 pb-3 space-y-1 mx-auto bg-white shadow-lg rounded-md">
        {% if user.is_authenticated %}
            <span class="block text-[#32869A] text-left mb-6">Welcome, {{ user.username }}</span> 
            <a href="{% url 'main:logout' %}" class="block relative px-4 py-3 bg-gradient-to-r from-[#73daf1] to-[#eb7acb] rounded-md justify-center items-center gap-2.5 flex transform transition duration-300 ease-in-out hover:scale-105 hover:shadow-lg">
                <div class="text-slate-50 text-xl font-sans font-bold">Logout</div>
            </a>
        {% else %}
            <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
                Login
            </a>
            <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                Register
            </a>
        {% endif %}
    </div>
</div>

<script>
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");
    const hamburger = document.querySelector(".hamburger");
    const xIcon = document.querySelector(".x-icon");

    btn.addEventListener("click", () => {
        menu.classList.toggle("hidden");
        hamburger.classList.toggle("hidden");
        xIcon.classList.toggle("hidden");
    });
</script>