dairy_products_ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, add_product_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete-product/<uuid:id>', delete_product, name='delete_product'),
    path('create-ajax', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    fat_content = models.CharField(max_length=50)
    quantity = models.IntegerField()
    rating = models.DecimalField(max_digits=3, decimal_places=2)

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class DairyEntryForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "fat_content", "quantity", "rating"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_price(self):
        price = self.cleaned_data["price"]
        return strip_tags(price)
    
    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)
    
    def fat_content(self):
        fat_content = self.cleaned_data["fat_content"]
        return strip_tags(fat_content)
    
    def clean_quantity(self):
        quantity = self.cleaned_data["quantity"]
        return strip_tags(quantity)
    
    def clean_rating(self):
        rating = self.cleaned_data["rating"]
        return strip_tags(rating)

main/views.py
from django.shortcuts import render, redirect, reverse
from main.forms import DairyEntryForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse

@login_required(login_url='/login')
def show_main(request):

    context = {
        'name': request.user.username,
        'class': 'PBP F',
        'npm': '2306165761',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

# function untuk menambahkan product
def create_product(request):
    form = DairyEntryForm(request.POST or None)

    # jika methodnya POST, maka save formnya dan redirect ke show_main
    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:show_main')

    # jika selain POST request, tampilkan main.html beserta context
    context = {'form': form}
    return render(request, "create_product.html", context)

# mengembalikan data dalam bentuk xml
def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

# mengembalikan data dalam bentuk json
def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# mengembalikan data dalam bentuk xml, mengambilnya berdasarkan id
def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

# mengembalikan data dalam bentuk json, mengambilnya berdasarkan id
def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, "Invalid username or password. Please try again.")

    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan id
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = DairyEntryForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get product berdasarkan id
    product = Product.objects.get(pk = id)
    # Hapus product
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = strip_tags(request.POST.get("price"))
    description = strip_tags(request.POST.get("description"))
    fat_content = strip_tags(request.POST.get("fat_content"))
    quantity = strip_tags(request.POST.get("quantity"))
    rating = strip_tags(request.POST.get("rating"))
    user = request.user

    new_product = Product(
        name=name, price=price, description=description,
        fat_content=fat_content, quantity=quantity, rating=rating,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"],
            fat_content=data["fat_content"],
            quantity=int(data["quantity"]),
            rating=float(data["rating"])
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_info.html
<div class="w-[382px] h-[52px] relative">
  <div class="w-[123px] h-[52px] left-0 top-0 absolute bg-white rounded-tl-[40px] rounded-bl-[40px] border border-[#dedede]"></div>
  <div class="w-[259px] h-[52px] left-[123px] top-0 absolute bg-gradient-to-l from-[#ffd3f2] to-[#cef6ff] rounded-tr-[40px] rounded-br-[40px] border border-[#dedede]"></div>
  <div class="left-[37px] top-[12px] absolute text-transparent bg-gradient-to-r from-[#73daf1] to-[#eb7acb] bg-clip-text text-xl font-bold font-sans">{{ title }}</div>
  <div class="left-[156px] top-[12px] absolute text-[#32869a] text-xl font-bold font-sans">{{ value }}</div>
</div>

main/templates/card_product.html
{% load static %}
<div class="px-[40px]">
    <div class="w-[380px] h-auto flex-col justify-start items-end inline-flex"> 
        <div class="self-stretch pb-6 bg-gradient-to-l from-[#ffd3f2] to-[#cef6ff] rounded-3xl border border-[#dedede] flex-col justify-start items-start gap-6 flex">
            <div class="self-stretch p-6 bg-white rounded-tl-3xl rounded-tr-3xl border border-[#dedede] justify-start items-center inline-flex">
                <div class="grow shrink basis-0 text-[#4ab2c9] text-2xl font-bold font-sans">
                    {{ product.name }}
                </div>
                <div class="px-6 py-2.5 bg-gradient-to-r from-[#73daf1] to-[#eb7acb] rounded-[40px] justify-center items-center gap-2.5 flex">
                    <div class="text-white text-xl font-bold font-sans">
                        {{ product.price }}
                    </div>
                </div>
            </div>
            <div class="self-stretch grow shrink basis-0 px-6 justify-start items-start gap-2.5 inline-flex">
                <div class="grow shrink basis-0 text-black text-xl font-normal font-sans">
                    {{ product.description }}
                </div>
            </div>
            <div class="self-stretch h-auto px-6 flex-col justify-start items-start gap-2 flex">
                <div class="justify-start items-center gap-2 inline-flex">
                    <div class="w-6 h-6 relative">
                        <img src="{% static 'image/fat.svg' %}" class="w-6 h-6" alt="Fat Icon"/>
                    </div>
                    <div class="text-black text-xl font-normal font-sans">
                        Fat - {{ product.fat_content }}
                    </div>
                </div>
                <div class="justify-start items-center gap-2 inline-flex">
                    <div class="w-6 h-6 relative">
                        <img src="{% static 'image/information.svg' %}" class="w-6 h-6" alt="Quantity Icon"/>
                    </div>
                    <div class="text-black text-xl font-normal font-sans">
                        Quantity - {{ product.quantity }}
                    </div>
                </div>
                <div class="self-stretch justify-start items-center gap-2 inline-flex">
                    <div class="w-6 h-6 relative">
                        <img src="{% static 'image/star.svg' %}" class="w-6 h-6" alt="Rating Icon"/>
                    </div>
                    <div class="text-black text-xl font-normal font-sans">
                        Rating - {{ product.rating }}
                    </div>
                </div>
                <div class="w-full"></div> 
            </div>
        </div>
        <div class="h-[65.50px] px-6 justify-end items-center gap-3 inline-flex">
            <div class="w-[64.50px] h-[65.50px] relative">
                <a href="{% url 'main:edit_product' product.pk %}" class="group">
                    <img src="{% static 'image/edit.svg' %}" class="w-20 h-20 top-[-50px] absolute transition-transform duration-300 ease-in-out group-hover:scale-110" />
                </a>
            </div>
            <div class="w-[64.50px] h-[65.50px] relative">
                <a href="{% url 'main:delete_product' product.pk %}" class="group">
                    <img src="{% static 'image/delete.svg' %}" class="w-20 h-20 top-[-50px] absolute transition-transform duration-300 ease-in-out group-hover:scale-110" />
                </a>
            </div>            
        </div>       
    </div>
</div>

main/templates/create_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Create Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 mb-16 max-w-xl">
    <h1 class="text-3xl font-bold font-sans text-transparent bg-gradient-to-r from-[#73daf1] to-[#eb7acb] bg-clip-text text-center mt-4 mb-8">
      Create Product
    </h1>    
    <div class="bg-white shadow-md rounded-lg px-12 py-4 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="mb-6 bg-gradient-to-r from-[#73daf1] to-[#eb7acb] text-white font-semibold px-6 py-3 rounded-lg w-full transform transition duration-300 ease-in-out hover:scale-105 shadow-lg">
              Create Product
          </button>
      </div>
      
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Edit Product</h1>
  
    <div class="bg-white rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
                      {{ field.label }}
                  </label>
                  <div class="w-full">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex justify-center mt-6">
            <button type="submit" class="bg-[#37899C] text-white font-semibold px-6 py-3 rounded-lg hover:bg-[#1F6272] transition duration-300 ease-in-out w-full">
                Edit Product
            </button>            
          </div>
      </form>
  </div>
  </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center w-screen bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-transparent bg-gradient-to-r from-[#73daf1] to-[#eb7acb] bg-clip-text text-3xl font-extrabold">
        Login to your account
      </h2>    
    </div>
    <form class="mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-[#73daf1] focus:border-[#73daf1] focus:z-10 sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-[#eb7acb] focus:border-[#eb7acb] focus:z-10 sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-gradient-to-r from-[#73daf1] to-[#eb7acb] transition-transform duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Sign in
        </button>      
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-black">
        Don't have an account yet?
        <a href="{% url 'main:register' %}" 
          class="font-medium bg-gradient-to-r from-[#73daf1] to-[#eb7acb] bg-clip-text text-transparent hover:text-black">
            Register Now
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8 form-style">
    <div>
      <h2 class="mt-6 text-center text-transparent bg-gradient-to-r from-[#73daf1] to-[#eb7acb] bg-clip-text text-3xl font-extrabold">
        Create your account
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        {% for field in form %}
          <div class="{% if not forloop.first %}mt-4{% endif %}">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-black">
              {{ field.label }}
            </label>
            <div class="relative">
              {{ field }}
              <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                {% if field.errors %}
                  <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                {% endif %}
              </div>
            </div>
            {% if field.errors %}
              {% for error in field.errors %}
                <p class="mt-1 text-sm text-red-600">{{ error }}</p>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-gradient-to-r from-[#73daf1] to-[#eb7acb] transition-transform duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Register
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <span class="block sm:inline">{{ message }}</span>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-black">
        Already have an account?
        <a href="{% url 'main:login' %}"
          class="font-medium bg-gradient-to-r from-[#73daf1] to-[#eb7acb] bg-clip-text text-transparent hover:text-black">
          Login here
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}